import { Check, X } from 'lucide-react'
import type { CustomerDetails } from '../types'

type FieldErrors = Partial<Record<keyof CustomerDetails, string>>
type CheckoutModalProps = { details: CustomerDetails; total: number; error: string; fieldErrors: FieldErrors; isSubmitting: boolean; onDetailsChange: (details: CustomerDetails) => void; onClose: () => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }

export function CheckoutModal({ details, total, error, fieldErrors, isSubmitting, onDetailsChange, onClose, onSubmit }: CheckoutModalProps) {
  return <div className="overlay checkout-overlay"><form className="checkout-modal" onSubmit={onSubmit}><div className="drawer-head"><div><p className="eyebrow">Almost there</p><h2>Delivery details</h2></div><button className="icon-button" onClick={onClose} type="button" aria-label="Close checkout" disabled={isSubmitting}><X size={20} /></button></div><p className="checkout-note">Your order is sent to the live kitchen and tracked in real time.</p><label>Name<input required disabled={isSubmitting} aria-invalid={Boolean(fieldErrors.name)} value={details.name} onChange={(event) => onDetailsChange({ ...details, name: event.target.value })} placeholder="Alex Morgan" />{fieldErrors.name && <small className="field-error">{fieldErrors.name}</small>}</label><label>Address<input required disabled={isSubmitting} aria-invalid={Boolean(fieldErrors.address)} value={details.address} onChange={(event) => onDetailsChange({ ...details, address: event.target.value })} placeholder="12 Willow Street" />{fieldErrors.address && <small className="field-error">{fieldErrors.address}</small>}</label><label>Phone number<input required disabled={isSubmitting} aria-invalid={Boolean(fieldErrors.phone)} type="tel" inputMode="tel" pattern="[0-9 +()-]{8,}" value={details.phone} onChange={(event) => onDetailsChange({ ...details, phone: event.target.value })} placeholder="(555) 123-4567" />{fieldErrors.phone && <small className="field-error">{fieldErrors.phone}</small>}</label>{error && <p role="alert" className="checkout-error">{error}</p>}<div className="checkout-total"><span>You'll pay</span><strong>${total.toFixed(2)}</strong></div><button className="primary-button checkout-button" type="submit" disabled={isSubmitting}>{isSubmitting ? 'Submitting order...' : 'Place order'} {isSubmitting ? <span className="button-spinner" aria-hidden="true" /> : <Check size={17} />}</button></form></div>
}
